### ISSUE TITLE
First time push  - error: failed to push some refs 

### ISSUE THREAD

**Issue by HungerMadra** [HungerMadra/java-CRUD-serialization#1]
error: failed to push some refs to 'https://github.com/aeziolis/java-CRUD-serialization.git'
eziolise@Anierobis-MacBook-Air FilmRating % 

I'm trying to push code to GitHub. This is a first for me, not sure what's breaking but I get the above error.

**Comment by B1910668-TN** [comment]
You can solve the problem by referring to the link below: https://docs.github.com/en/get-started/importing-your-projects-to-github/importing-source-code-to-github/adding-locally-hosted-code-to-github?platform=mac

If you still get the error, please take a screenshot so I can better understand the problem you're having.
